appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: axFwzTAgVLRC8Df9P+YTEICEFgjQfMBiDf4J6z2ecy3V+wtSF4xqp7LRRUmztkYjzAUdgCIiqtgfUD8ARDHo7bLynPgotug+bXCUbLNtJWHt+aeGKqIN507zjfr5rWSErz9m5ZtLIxxlUKjv9wJck91xxTy+vaaiIBD7NpjTQkrqc+3vOAiRGuIfYMX7ml1gWBBWNLZ3hU00vFipizLKR0v2YXpthsyY4vB1VedEaMgwwmlM2j/GGnR/tSRiwsDoMRtSwWJby5mCG2Z8x8OpBO36M6mwwEeXDhqvX/Kig7U6aBMxJ3VOALFWZMBNOGuSpF9ZzXsx2iZfz5SySqNEe72sOPLa7cf3kRBPnoZK4t/693x3Dt6gZcP0/8lVbmhqtCfnZFUTCBdPP5Wj7k3nCGQKTHg5QKELRpMtfAxQdWIklXVvc+HVXyK9zIlPpc8x86c9pqc+l2pBaUG9/ZnhJmtsAgLDz8GxK1IeM5nqEzy6ANWcQ50qXoSucq3qLdw8UrZ5hfDY1xsBIc9cpwC9cDBpM268tGIC4Z0Bse5E1EPdrY9JWXZz+tHuOiWoECdMxD1MRVE4ePJMz3vWuRFthPuI1vLV3NVBjUs2oWPBZ59BqLZpCvgzIKZSy8plnFO6rwpOAep/k7e5IADbPWpyDtPbxQ1XkdsQDTheH0fGsjo=}
